spring:
  datasource:
    url: jdbc:h2:mem:registeredUser
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    naming:
      physical-strategy: org.hibernate.boot.model.naming.registeredUser
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.registeredUser